version: '3'

services:

  app:
    build: .
    environment: 
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    command: sh -c "npm install nodemon -g && nodemon src/app.js"
    volumes:
      - ./src:/app/src
    depends_on:
      - mongo
    ports:
      - 5000:3000

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}